/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stdio.h>
#include <stdint.h>
#include "SYSTIC.h"
#include "uart.h"
#include "DHT22.h"

DHT_DATA sensor;
int main(void)
{
	uart2_tx_init();
    while(1)
    {
        if(DHT22_DATA(&sensor))
        {
            printf("Temp = %d.%dC\r\n", (sensor.temperature/10),(sensor.temperature%10));
            printf("Humidity = %d.%d%%\r\n",(sensor.humidity/10),(sensor.humidity%10));
        }
        uS_delay(100000);
    }
}



